networks:
  spotify-network:
    name: spotify-network
    driver: bridge

services:
  spotify-backofficep:
    container_name: spotify-backofficep-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: build
      args:
        DATABASE_URL: ${DATABASE_URL}
        MINIO_ENDPOINT_INTERNAL: ${MINIO_ENDPOINT_INTERNAL}
        MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
        MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    image: spotify-backofficep-dev:latest
    command: ["npm", "run", "dev"]
    networks:
      - spotify-network
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
